#! /usr/bin/env python3

import jsonFileGenerator
import skillList
import argparse

optionsParser = argparse.ArgumentParser()
optionsParser.add_argument('-o', '--output', required=True)
optionsParser.add_argument('-s', '--skill-tree', required=True)
options = optionsParser.parse_args()
print(options)

skills = skillList.SkillList.readSkillList(options.skill_tree)
skills.checkDag()
jsonFileGenerator.generateFiles(skills, options.output + '/leveledSkills')
reducedList = skills.mergeLevels()
jsonFileGenerator.generateFiles(reducedList, options.output + '/mergedSkills')
