#! /usr/bin/env python3

# Copyright 2018 Nathanael Hübbe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import jsonFileGenerator
import skillList
import argparse

optionsParser = argparse.ArgumentParser()
optionsParser.add_argument('-o', '--output', required=True)
optionsParser.add_argument('-s', '--skill-tree', required=True)
options = optionsParser.parse_args()
print(options)

skills = skillList.SkillList.readSkillList(options.skill_tree)
skills.checkDag()
jsonFileGenerator.generateFiles(skills, options.output + '/leveledSkills')
reducedList = skills.mergeLevels()
jsonFileGenerator.generateFiles(reducedList, options.output + '/mergedSkills')
